(function($){"use strict";function preloaderLoad(){if($('.preloader').length){$('.preloader').delay(200).fadeOut(300);}
$(".preloader_disabler").on('click',function(){$("#preloader").hide();});}
function navbarScrollfixed(){if(typeof $.fn.scrollToFixed=='undefined')return;$('.navbar-scrolltofixed').scrollToFixed();var summaries=$('.summary');summaries.each(function(i){var summary=$(summaries[i]);var next=summaries[i+1];summary.scrollToFixed({marginTop:$('.navbar-scrolltofixed').outerHeight(true)+10,limit:function(){var limit=0;if(next){limit=$(next).offset().top-$(this).outerHeight(true)-10;}else{limit=$('.footer').offset().top-$(this).outerHeight(true)-10;}
return limit;},zIndex:999});});}
$(document).on('ready',function(){$("#respMenu").aceResponsiveMenu({resizeWidth:'768',animationSpeed:'fast',accoridonExpAll:false});});function mobileNavToggle(){if($('#main-nav-bar .navbar-nav .sub-menu').length){var subMenu=$('#main-nav-bar .navbar-nav .sub-menu');subMenu.parent('li').children('a').append(function(){return '<button class="sub-nav-toggler"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>';});var subNavToggler=$('#main-nav-bar .navbar-nav .sub-nav-toggler');subNavToggler.on('click',function(){var Self=$(this);Self.parent().parent().children('.sub-menu').slideToggle();return false;});};}
$('.tags-bar > span i').on('click',function(){$(this).parent().fadeOut();});$(window).on('scroll',function(){if($('.scroll-to-top').length){var strickyScrollPos=100;if($(window).scrollTop()>strickyScrollPos){$('.scroll-to-top').fadeIn(500);}else if($(this).scrollTop()<=strickyScrollPos){$('.scroll-to-top').fadeOut(500);}};if($('.stricky').length){var headerScrollPos=$('.header-navigation').next().offset().top;var stricky=$('.stricky');if($(window).scrollTop()>headerScrollPos){stricky.removeClass('slideIn animated');stricky.addClass('stricky-fixed slideInDown animated');}else if($(this).scrollTop()<=headerScrollPos){stricky.removeClass('stricky-fixed slideInDown animated');stricky.addClass('slideIn animated');}};});$(".mouse_scroll, .mouse_scroll.home8").on('click',function(){$('html, body').animate({scrollTop:$("#feature-property, #property-city").offset().top},1000);});$(document).on('ready',function(){$('.collapse').on('show.bs.collapse',function(){$(this).siblings('.card-header').addClass('active');});$('.collapse').on('hide.bs.collapse',function(){$(this).siblings('.card-header').removeClass('active');});$(function(){$('[data-toggle="tooltip"]').tooltip()})});$(document).on('ready',function(){$('.cart_btn').children('ul.cart').children('li').each(function(indexCount){$(this).children('ul.dropdown_content').children('li').each(function(index){var delay=0.1+index*0.03;$(this).css("animation-delay",delay+"s")});});});jQuery(document).ready(function($){var wHeight=window.innerHeight;$('#mk-fullscreen-searchform').css('top',wHeight/2);jQuery(window).resize(function(){wHeight=window.innerHeight;$('#mk-fullscreen-searchform').css('top',wHeight/2);});$('#search-button, #search-button2').on('click',function(){console.log("Open Search, Search Centered");$("div.mk-fullscreen-search-overlay").addClass("mk-fullscreen-search-overlay-show");});$("button.mk-fullscreen-close").on('click',function(){console.log("Closed Search");$("div.mk-fullscreen-search-overlay").removeClass("mk-fullscreen-search-overlay-show");});});function counterNumber(){$('div.timer').counterUp({delay:5,time:2000});}
$(function(){$('nav#menu').mmenu();});$(function(){if($('#slider-range').length){$("#slider-range").slider({range:true,min:50,max:150,values:[50,120],slide:function(event,ui){$("#amount").val("$"+ui.values[0]+" - $"+ui.values[1]);}});$("#amount").val("$"+$("#slider-range").slider("values",0)+
" - $"+$("#slider-range").slider("values",1));}});$(document).on('ready',function(){var maxvalue=$("#max_value").val();if($('.slider-range').length){$(".slider-range").slider({range:true,min:0,max:maxvalue,values:[0,maxvalue],slide:function(event,ui){$(".amount").val(ui.values[0]);$(".amount2").val(ui.values[1]);}});$(".amount").change(function(){$(".slider-range").slider('values',0,$(this).val());});$(".amount2").change(function(){$(".slider-range").slider('values',1,$(this).val());});}});if($('.progress-levels .progress-box .bar-fill').length){$(".progress-box .bar-fill").each(function(){var progressWidth=$(this).attr('data-percent');$(this).css('width',progressWidth+'%');$(this).children('.percent').html(progressWidth+'%');});}
var isMobile={Android:function(){return navigator.userAgent.match(/Android/i);},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i);},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i);},Opera:function(){return navigator.userAgent.match(/Opera Mini/i);},Windows:function(){return navigator.userAgent.match(/IEMobile/i);},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows());}};jQuery(document).on('ready',function(){jQuery(window).stellar({horizontalScrolling:false,hideDistantElements:true,verticalScrolling:!isMobile.any(),scrollProperty:'scroll',responsive:true});});if(($(".popup-img").length>0)||($(".popup-iframe").length>0)||($(".popup-img-single").length>0)){$(".popup-img").magnificPopup({type:"image",gallery:{enabled:true,}});$(".popup-img-single").magnificPopup({type:"image",gallery:{enabled:false,}});$('.popup-iframe').magnificPopup({disableOn:700,type:'iframe',preloader:false,fixedContentPos:false});$('.popup-youtube, .popup-vimeo, .popup-gmaps').magnificPopup({disableOn:700,type:'iframe',mainClass:'mfp-fade',removalDelay:160,preloader:false,fixedContentPos:false});};$('#myTab a').on('click',function(e){e.preventDefault()
$(this).tab('show')})
function wowAnimation(){var wow=new WOW({animateClass:'animated',mobile:true,offset:0});wow.init();}
if($('.datepicker').length){$('.datepicker').datetimepicker();}
if($('#maximage').length){$('#maximage').maximage({cycleOptions:{fx:'fade',speed:500,timeout:20000,prev:'#arrow_left',next:'#arrow_right'},onFirstImageLoaded:function(){jQuery('#cycle-loader').hide();jQuery('#maximage').fadeIn('fast');}});jQuery('#html5video').maximage('maxcover');jQuery('.in-slide-content').delay(2000).fadeIn();}
if($('.tes-for').length){$('.tes-for').slick({slidesToShow:1,slidesToScroll:1,arrows:false,fade:false,autoplay:false,autoplaySpeed:2000,asNavFor:'.tes-nav'});$('.tes-nav').slick({slidesToShow:5,slidesToScroll:1,asNavFor:'.tes-for',dots:false,arrows:false,centerPadding:'1px',centerMode:true,focusOnSelect:true});}
if($('.feature_property_slider').length){var isMulti=($('.feature_property_slider .item').length>1)?true:false
$('.feature_property_slider').owlCarousel({rtl:bookingCore.rtl,loop:isMulti,margin:30,dots:isMulti,nav:false,autoplayHoverPause:false,autoplay:false,singleItem:true,smartSpeed:1200,navText:['<i class="fa fa-arrow-left"></i>','<i class="fa fa-arrow-right"></i>'],responsive:{0:{items:1,center:false},480:{items:1,center:false},600:{items:1,center:false},768:{items:2},992:{items:2},1200:{items:2},1280:{items:3}}})}
if($('.testimonial_grid_slider').length){var isMulti=($('.testimonial_grid_slider .item').length>1)?true:false
$('.testimonial_grid_slider').owlCarousel({rtl:bookingCore.rtl,loop:isMulti,margin:15,dots:isMulti,nav:false,autoplayHoverPause:false,autoplay:false,singleItem:true,smartSpeed:1200,navText:['<i class="fa fa-arrow-left"></i>','<i class="fa fa-arrow-right"></i>'],responsive:{0:{items:1,center:false},480:{items:1,center:false},600:{items:1,center:false},768:{items:1},992:{items:1},1200:{items:1}}})}
if($('.team_slider').length){$('.team_slider').owlCarousel({loop:true,margin:30,dots:false,nav:true,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,singleItem:true,smartSpeed:1200,navText:['<i class="flaticon-left-arrow"></i>','<i class="flaticon-right-arrow"></i>'],responsive:{0:{items:1,center:false},480:{items:1,center:false},520:{items:2,center:false},600:{items:2,center:false},768:{items:2},992:{items:3},1200:{items:4},1366:{items:4},1400:{items:4}}})}
if($('.best_property_slider').length){$('.best_property_slider').owlCarousel({loop:true,margin:30,dots:true,nav:false,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,singleItem:true,smartSpeed:1200,navText:['<i class="flaticon-left-arrow"></i>','<i class="flaticon-right-arrow"></i>'],responsive:{0:{items:1,center:false},480:{items:1,center:false},520:{items:1,center:false},600:{items:2,center:false},768:{items:2},992:{items:3},1200:{items:3},1366:{items:4},1400:{items:4}}})}
if($('.feature_property_home3_slider').length){$('.feature_property_home3_slider').owlCarousel({loop:true,margin:30,dots:false,nav:true,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,singleItem:true,smartSpeed:1200,navText:['<i class="flaticon-left-arrow"></i>','<i class="flaticon-right-arrow"></i>'],responsive:{0:{items:1,center:false},480:{items:1,center:false},520:{items:2,center:false},600:{items:2,center:false},768:{items:2},992:{items:3},1200:{items:4},1366:{items:4},1400:{items:4}}})}
if($('.feature_property_home6_slider').length){$('.feature_property_home6_slider').owlCarousel({loop:true,margin:30,dots:false,nav:true,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,singleItem:true,smartSpeed:1200,navText:['<i class="flaticon-left-arrow"></i>','<i class="flaticon-right-arrow"></i>'],responsive:{0:{items:1,center:false},480:{items:1,center:false},520:{items:2,center:false},600:{items:2,center:false},768:{items:2},992:{items:3},1200:{items:4},1366:{items:4},1400:{items:4}}})}
if($('.our_agents_home6_slider').length){$('.our_agents_home6_slider').owlCarousel({loop:true,margin:30,dots:false,nav:true,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,singleItem:true,smartSpeed:1200,navText:['<i class="flaticon-left-arrow"></i>','<i class="flaticon-right-arrow"></i>'],responsive:{0:{items:1,center:false},480:{items:1,center:false},520:{items:2,center:false},600:{items:2,center:false},768:{items:2},992:{items:3},1200:{items:4},1366:{items:4},1400:{items:5}}})}
if($('.testimonial_slider_home9').length){$('.testimonial_slider_home9').owlCarousel({loop:true,margin:30,dots:true,nav:false,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,singleItem:true,smartSpeed:1200,navText:['<i class="fa fa-arrow-left"></i>','<i class="fa fa-arrow-right"></i>'],responsive:{0:{items:1,center:false},480:{items:1,center:false},600:{items:1,center:false},768:{items:2},992:{items:2},1200:{items:2},1280:{items:2}}})}
if($('.sidebar_feature_property_slider').length){var isMulti=($('.sidebar_feature_property_slider .item').length>1)?true:false
$('.sidebar_feature_property_slider').owlCarousel({animateIn:'fadeIn',loop:isMulti,margin:15,items:1,dots:isMulti,nav:false,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,smartSpeed:2000,singleItem:true,navText:['<i class="flaticon-left-arrow-1"></i>','<i class="flaticon-right-arrow"></i>'],responsive:{320:{items:1,center:false},480:{items:1,center:false},600:{items:1,center:false},768:{items:1},992:{items:1},1200:{items:1}}})}
if($('.listing_single_property_slider').length){$('.listing_single_property_slider').owlCarousel({animateIn:'fadeIn',loop:true,margin:2,dots:false,nav:true,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,smartSpeed:2000,singleItem:true,navText:['<i class="flaticon-left-arrow-1"></i>','<i class="flaticon-right-arrow"></i>'],responsive:{320:{items:1,center:false},480:{items:1,center:false},600:{items:1,center:false},768:{items:2},992:{items:3},1200:{items:3}}})}
if($('.fp_single_item_slider').length){$('.fp_single_item_slider').owlCarousel({loop:true,margin:15,dots:false,nav:true,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,smartSpeed:2000,singleItem:true,navText:['<i class="flaticon-left-arrow-1"></i>','<i class="flaticon-right-arrow"></i>'],responsive:{320:{items:1,center:false},480:{items:1,center:false},600:{items:1,center:false},768:{items:1},992:{items:1},1200:{items:1}}})}
if($(".banner-style-one").length){$(".banner-style-one").owlCarousel({loop:true,items:1,margin:0,dots:true,nav:true,rtl:bookingCore.rtl,animateOut:"slideOutDown",animateIn:"fadeIn",active:true,smartSpeed:1000,autoplay:false});$(".banner-carousel-btn .left-btn").on("click",function(){$(".banner-style-one").trigger("next.owl.carousel");return false;});$(".banner-carousel-btn .right-btn").on("click",function(){$(".banner-style-one").trigger("prev.owl.carousel");return false;});}
if($('.single_product_slider').length){$('.single_product_slider').owlCarousel({loop:true,margin:30,dots:true,nav:false,rtl:bookingCore.rtl,autoplayHoverPause:false,autoplay:false,singleItem:true,smartSpeed:1200,navText:['<i class="flaticon-left-arrow"></i>','<i class="flaticon-right-arrow"></i>'],responsive:{0:{items:1,center:false},480:{items:1,center:false},520:{items:1,center:false},600:{items:1,center:false},768:{items:1},992:{items:1},1200:{items:1},1366:{items:1},1400:{items:1}}})}
function scrollToTop(){$(window).scroll(function(){if($(this).scrollTop()>600){$('.scrollToHome').fadeIn();}else{$('.scrollToHome').fadeOut();}});$('.scrollToHome').on('click',function(){$('html, body').animate({scrollTop:0},800);return false;});}
$(document).on('ready',function(){$("#show_advbtn, #show_advbtn2").on('click',function(){$(".dropdown-content").show();});$("#hide_advbtn, #hide_advbtn2").on('click',function(){$(".dropdown-content").hide();});$("#show_advbtn, #show_advbtn2").on('click',function(){$("body").addClass("mobile_ovyh");});$("#show_advbtn, #show_advbtn2").on('click',function(){$("body").removeClass("mobile_ovyh");});$('.property_select_price').on('click',function(){console.log(1)
$(".property_select_price--slider").toggle();})
$(".filter_open_btn").on('click',function(){$(".sidebar_content_details.style3").addClass("sidebar_ml0");});$(".filter_closed_btn").on('click',function(){$(".sidebar_content_details.style3").removeClass("sidebar_ml0");});$(".filter_open_btn").on('click',function(){$("body").addClass("body_overlay");});$(".filter_closed_btn").on('click',function(){$("body").removeClass("body_overlay");});$(".overlay_close").on('click',function(){$(".white_goverlay").toggle(500);});$('.sticky-nav-tabs-container li').on('click',function(){$('.sticky-nav-tabs-container li').removeClass('active');$(this).addClass('active');});});$(document).on('ready',function(){navbarScrollfixed();scrollToTop();wowAnimation();mobileNavToggle();$.fn.extend({toggleText:function(a,b){return this.text(this.text()==b?a:b);}});if($('.showFilter').length){$('.showFilter').on('click',function(){$(this).toggleText('Show Filter','Hide Filter');$(this).toggleClass('flaticon-close flaticon-filter-results-button sidebarOpended sidebarClosed');$('.listing_toogle_sidebar.sidenav').toggleClass('opened');$('.body_content').toggleClass('translated');});}
$.fn.extend({toggleText2:function(a,b){return this.text(this.text()==b?a:b);}});if($('.showBtns').length){$('.showBtns').on('click',function(){$(this).toggleText2('Show Filter','Hide Filter');$(this).toggleClass('flaticon-close flaticon-filter-results-button sidebarOpended2 sidebarClosed2');$('.sidebar_content_details').toggleClass('is-full-width');});}});$(window).on('load',function(){counterNumber();preloaderLoad();});$(window).on('scroll',function(){});})(window.jQuery);